#updated cloud.properties
#Tue Feb 03 13:25:28 IST 2026
ADOproject=HaloCRM_SAFe
ADOtestplanID=7171802
ADOtestsuiteID=17110895
ADOtoken=QWJ1ZmFpemFsLmFiZHVsYWplZXMuY29udHJhY3RvckBwZXBzaWNvLmNvbTpEV0s2OUFnU3hxMDBaWHNwY2VzYjhTcENZWkJHS2JLODNsRzRKdGdqZmJpM3FkQUVEek9CSlFRSjk5QUtBQ0FBQUFBZkpRdndBQUFTQVpET2lSNXg\=
Device_URL=https\://pepsico.experitest.com/index.html\#/opendevice/25030/1
ExecutionSheetName=DriverScript_R4.3.xlsx
MyName=Gunasekhar
Myfirstcompany=Cognizant
accessKey=eyJhbGciOiJIUzI1NiJ9.eyJ4cC51Ijo1NDgxNDMsInhwLnAiOjEsInhwLm0iOjE2NzcxNzAyNjIwMTEsImV4cCI6MTk5MjUzMDI4OCwiaXNzIjoiY29tLmV4cGVyaXRlc3QifQ.EPB9QAM9w5LNv7ir2MyT91Ky5YNi2plS0rvV-METe5M
chrome_version=112.0.5615.28
chromedriver=\\halo_automation\\src\\test\\resources\\driver\\chromedriver.exe
device=@os\='ios' and @serialnumber\='00008110-000479A10AF1801E'
password=
project=
url=https\://pepsico.experitest.com
username=
workBenchurl=https\://workbench.developerforce.com/login.php?startUrl\=%2Fdescribe.php
